### ISSUE TITLE
Regression in support for click 7.* in main branch (1.7.0dev, unreleased)

### ISSUE THREAD

**Issue by dwreeves** [ewels/rich-click#112]
Was adding a matrix strategy to the CI and noticed the following:

```
git checkout main
pip install -U "click<8"
python examples/01_simple.py
```

Result: No output at all, and exit code 0.

I bring this up because the `setup.py` says that `click>=7` is supported.

It's possible I can get around to fixing this as part of my CI changes. There is a hint as to at least one thing that may be going on with the pytest results.

**Comment by ewels** [comment]
If it's too much hassle then I'm happy to drop support for Click 7 too. Click 8 was released over 2 years ago so it's been around a while. But if it's an easy fix, then.. 🤷🏻‍♂️

**Comment by dwreeves** [comment]
The actual fix in the code wasn't hard. I do need to however figure out how to fix the test suite breaking. I suppose if I cannot figure out how to fix the test suite we can just keep the fix in the code but not cover it by the tests/CI. But, let's just wait, I have a few more hours in me of work on this 7.x problem I haven't gotten to yet.

**Comment by dwreeves** [comment]
Quick update on this. I did need to make a few changes to the code and to the test suite to get Click 7.x compatibility. I'll hopefully show my work soon.

The main thing I am struggling with right now is the suite of tests that use `rich_config`. For each of these, the output is blank. Everything else is looking good though.

I'm deciding whether this is a feature that can be supported in 7.x or whether the user should be warned doesn't work.
