### ISSUE TITLE
Add support for Typer

### ISSUE THREAD

**Issue by Benjamin-Lee** [ewels/rich-click#14]
This looks great! Thank you for sharing this.

I tried using the import in a Typer project and (unsurprisingly) it didn't work. Even if there's no official code support for using this with Typer, some docs would be super helpful since I would love to use it for my CLI.

**Comment by wasi-master** [comment]
So I used [click-help-colors](https://github.com/click-contrib/click-help-colors) in my [pypi-command-line](https://github.com/wasi-master/pypi-command-line) project before and although click-help-colors officially wasn't supported for Typer. I found a workaround by searching for open issues in the Typer repository. https://github.com/tiangolo/typer/issues/47

I am not sure if the same solution could be used here, but if it works, then great.

**Comment by wasi-master** [comment]
So I tested a bit and found a workaround

```python
try:
    import rich_click as click
    from rich_click import RichCommand as Command, RichGroup as Group
except ImportError:
    import click
    from click import RichCommand as Command, RichGroup as Group

class MyTyper(typer.Typer):
    """A custom subclassed version of typer.Typer to allow rich help"""

    def __init__(self, *args, cls=Group, **kwargs) -> None:
        super().__init__(*args, cls=cls, **kwargs)

    def command(self, *args, cls=Command, **kwargs) -> typer.Typer.command:
        return super().command(*args, cls=cls, **kwargs)
```

Now this may not be the best solution but it works I guess. By the way this is an excerpt from my project so I may be missing some code, if that's the case be sure to mention me and I'll fix it

**Comment by ewels** [comment]
Super nice!

I guess then you need to use the custom class name `MyTyper` in your code.. I wonder if we can do the same trick for Typer that we do for Click and have a drop-in `import rich_click.typer as typer` 🤔 

I'm on holiday this week but will have a play when I'm back. Need to learn Typer first and get a minimal example to play with 😅

**Comment by Benjamin-Lee** [comment]
This worked for me! Thanks @wasi-master for the workaround.

**Comment by browniebroke** [comment]
Thanks for the snippet @wasi-master I tweaked it a bit to integrate it in my project: https://github.com/browniebroke/deezer-oauth-cli/pull/30/files

**Comment by wasi-master** [comment]
@browniebroke Well done!

**Comment by ewels** [comment]
@browniebroke - this looks great! Do you fancy prepping a PR to this repo with that, or are you happy if I pinch your code? I'm thinking that we can then have something like:

```python
import rich_click.typer as typer
```

**Comment by browniebroke** [comment]
I was just wondering what API you were envisioning, but what that suggestion, I think it's now all clear. I can definitely do that, yes.
