### ISSUE TITLE
Rich markup support in command epilog

### ISSUE THREAD

**Issue by carbon108** [ewels/rich-click#145]
Hi! 

We get an issue with rich markup in command `epilog`

For the command:
```python
@click.command("xyz", epilog="Example: [bold]xyz[/] --help")
def xyz():
    """Help XYZ"""
    pass
```

we find ` [bold]xyz[/]` in responce

![Screenshot_20231201_131127](https://github.com/ewels/rich-click/assets/9625791/9f467a6a-5650-4eda-bfc1-73bb3c0ea4f8)

How can one fix it? Advice is much appreciated

**Comment by carbon108** [comment]
Hello @dwreeves Thank you for the quick and detailed reply  So, please fix it if it's not an issue for you

**Comment by dwreeves** [comment]
@carbon108 -- `rich-click==1.7.2` has been released and fixes the issue. There is also a `STYLE_EPILOG_TEXT` config you can use if you'd like.

Example below:

```python
import rich_click as click

@click.command("xyz", epilog="Example: [bold]xyz[/] --help")
@click.rich_config(help_config=click.RichHelpConfiguration(use_rich_markup=True))
def xyz():
    """Help XYZ"""
    pass

xyz()
```

<img width="491" alt="image" src="https://github.com/ewels/rich-click/assets/31971762/a32375b9-f314-4da3-97b8-b37eca09719e">

**Comment by carbon108** [comment]
Thank you @dwreeves! Now it's working just fine
