### ISSUE TITLE
Support abort messages 

### ISSUE THREAD

**Issue by Benjamin-Lee** [ewels/rich-click#21]
From what I can see #2 styles usage errors, not runtime errors. This leads to strange error printouts during runtime when the usage will get printed out along with the error panel. Is there a way to just write out the error message? 

```
[16:54:27] INFO     Removing duplicate sequences...                                                                                 dedup.py:25
           ERROR    Unable to find Seqkit executable.                                                                               utils.py:14
Usage: bdltest easy-search [OPTIONS] FASTA
Try 'bdltest easy-search --help' for help.
╭─ Error ──────────────────────────────────────────────────────────────────────────────╮
│ Unable to find Seqkit executable. Are you sure that it's installed? To test if it    │
│ is, run the following command: seqkit version                                        │
╰──────────────────────────────────────────────────────────────────────────────────────╯
If you have any questions or need help, please contact me at https://benjamindlee.com
```

**Comment by Benjamin-Lee** [comment]
For reference, I do not get styled `click.exceptions.Abort` errors as would be expected from https://github.com/ewels/rich-click/blob/8378cddfab5087a0d7e8f21433212c3cf0ac6b00/src/rich_click/rich_click.py#L497-L511

**Comment by Benjamin-Lee** [comment]
D'oh, I think I get why — this is from the unreleased 1.1 code. Thanks again for the hard work @ewels!

**Comment by ewels** [comment]
Right! But I'm a bit confused that you got the weird output. For me, before I added the unreleased error handling code I got unhandled exceptions, not usage messages etc..

Have you tried running with the dev version yet?

**Comment by Benjamin-Lee** [comment]
@ewels just updated to 1.2.0 and I'm now getting the abort message when throwing a click.Abort. However, I'm not getting any output of the exception message like with a `UsageError`. Is there a way to get that or should I just manually print it for now?

Now:

```
[11:10:20] ERROR    Unable to find seqkit executable.                                                                               utils.py:18
Aborted.
```

Raising `click.UsageError`:

```
[11:10:51] ERROR    Unable to find seqkit executable.                                                                               utils.py:18
Usage: bdltest easy-search [OPTIONS] FASTA
Try 'bdltest easy-search --help' for help.
╭─ Error ──────────────────────────────────────────────────────────────────────────────╮
│ Unable to find seqkit executable. Are you sure that it's installed? To test if it    │
│ is, run the following command: seqkit                                                │
╰──────────────────────────────────────────────────────────────────────────────────────╯
If you have any questions or need help, please contact me at https://benjamindlee.com
```

**Comment by ewels** [comment]
Right - I assumed that `click.Abort` is mostly (only) used to handle cmd+c exits. I guess you're manually raising these exception types?

What does native click do? Can I see the code that you're using to raise these? I guess you're passing an argument to the exception which you'd like to be printed in the error box?

**Comment by ewels** [comment]
Note, I was styling the behaviour on [these click docs](https://click.palletsprojects.com/en/8.0.x/exceptions/#where-are-errors-handled):

> * If an [Abort](https://click.palletsprojects.com/en/8.0.x/api/#click.Abort) exception is raised print the string Aborted! to standard error and exit the program with exit code 1.

And yeah, [the source code](https://github.com/pallets/click/blob/d14ee193d01096113d5de0428b8552bcd5f368e9/src/click/core.py#L1092-L1096) doesn't seem to support custom messages.
