### ISSUE TITLE
Add rich-click to conda-forge

### ISSUE THREAD

**Issue by apcamargo** [ewels/rich-click#22]
The title says it all. Just to make it easier for other packages to depend on rich click :)

**Comment by ewels** [comment]
Yes, good suggestion. I'll do this 👌🏻🙂

**Comment by ewels** [comment]
PR to staged-recipes now up: https://github.com/conda-forge/staged-recipes/pull/18181

**Comment by ewels** [comment]
Merged, conda-forge feedstock now up: https://github.com/conda-forge/rich-click-feedstock

**Comment by ewels** [comment]
Ok, should now be available: https://anaconda.org/conda-forge/rich-click

**Comment by ewels** [comment]
Still can't find the package via `conda search` but as I can see the anaconda web page I am pretty confident it should be sorted now (I think the conda-forge listing just takes a little while to update).

I've added mention of this to the readme and am now closing the issue. Let me know if anything doesn't work as expected!
