### ISSUE TITLE
Wrapping not enabled on some columns, cutting off content

### ISSUE THREAD

**Issue by paw-lu** [ewels/rich-click#33]
Great project, thanks for sharing it!

I have some cli values with [a lot of possible values](https://nbpreview.readthedocs.io/en/latest/usage.html#cmdoption-nbpreview-t).

When `--help` is rendered via rich-click, the options are cut off.

```console
❯ nbp --help

 Usage: nbp [OPTIONS] FILE...

 Render a Jupyter Notebook in the terminal.

╭─ Options ────────────────────────────────────────────────────────────────────╮
│  *                        file  FILE...               Jupyter notebook       │
│                                                       file(s) to render on   │
│                                                       the terminal. Use a    │
│                                                       dash ('-') or pipe in  │
│                                                       data to the command    │
│                                                       to read from standard  │
│                                                       input.                 │
│                                                       [required]             │
│     --theme               -t    [default|emacs|frie…  The theme to use for   │
│                                                       syntax highlighting.   │
│                                                       Call                   │
│                                                       ``--list-themes`` to   │
│                                                       preview all available  │
│                                                       themes.                │
```

<img width="580" alt="Screen Shot 2022-03-02 at 9 44 21 PM" src="https://user-images.githubusercontent.com/30049606/156503866-0649eb72-1dcc-40bc-851d-ac3c13ccceba.png">

**Comment by ewels** [comment]
In this scenario it may be worth moving the metavars to be appended, see https://github.com/ewels/rich-click#metavars

Let me know if you have any suggestions on how to make this part of the docs easier to find, or better functionality.

I'm a little surprised that they're truncated though. Not sure where in the code this is being done. I'm going to leave this issue open until I investigate as it could be a rich table setting that I've overlooked or something.

**Comment by paw-lu** [comment]
> Ok yeah, it was rich that was truncating these strings. That should be solved now with the full list wrapping on to new lines.

Really appreciated, thanks!

> I've also improved the readme with a new example and some screenshots: https://github.com/ewels/rich-click#metavars-and-option-choices

Also, thanks. For reference, I didn't know that the list of possible values were known as metavars, but the new README changes makes that really clear.

Again, thanks for the project here!
