### ISSUE TITLE
Click `envvar` defaults not shown

### ISSUE THREAD

**Issue by ewels** [ewels/rich-click#36]
I don't think that `envvar` is considered currently: https://click.palletsprojects.com/en/8.0.x/options/#values-from-environment-variables

See https://github.com/ewels/rich-click/pull/26#issuecomment-1057669185

**Comment by ewels** [comment]
> I quite like the behaviour, so I think I'll add it as a default for both tools in the Typer style. I'll create an option to disable it.

Never mind, there's a `show_envvar` argument in click.

**Comment by taranlu-houzz** [comment]
@ewels Is there a way to disable this behavior for the default generated `--install-completion` and `--show-completion` commands?

**Comment by ewels** [comment]
So many options 🙈 Could you make a new issue for this please?

**Comment by taranlu-houzz** [comment]
@ewels Just created #84.
