### ISSUE TITLE
Is `click.MultiCommand` supported?

### ISSUE THREAD

**Issue by nilsvu** [ewels/rich-click#38]
Here's a minimal example using `click.MultiCommand` for lazy loading of subcommands. Is this already supported and I just haven't figured out how to use it, or is this not supported yet?

```py
import rich_click as click

class Cli(click.MultiCommand):
    def list_commands(self, ctx):
        return ["foo"]

    def get_command(self, ctx, name):
        if name == "foo":
            from foo import bar
            return bar
        raise NotImplementedError(f"The command '{name}' is not implemented.")

@click.group(cls=Cli)
def cli():
    pass
```

**Comment by ewels** [comment]
Rich-click works by overwriting the default `cls` used in the `@group` decorator, so if you define your own like in this example it will overwrite rich-click and use default click.

You can explicitly use the rich-click classes to get around this (see [example](https://github.com/ewels/rich-click/blob/main/examples/02_declarative.py)) but yeah - we don't have a `rich_click.MultiCommand` yet.

I guess it should be possible to add support for this though. Need to do something similar to the [`Command` one](https://github.com/ewels/rich-click/blob/main/src/rich_click/rich_command.py).

**Comment by ewels** [comment]
No ETA sorry, no. Happy to accept PRs to tackle this though.

**Comment by hsunner** [comment]
According to [click docs](https://click.palletsprojects.com/en/8.1.x/api/#click.MultiCommand) click.Command.format_help() method calls .format_usage(), .format_help_text(), .format_options() and .format_epilog() for the actual output. In contrast, [rich_format_help()](https://github.com/ewels/rich-click/blob/8e7523c891e0d3132f3c49e98154945e371d5e9b/src/rich_click/rich_click.py#L392), which is used in [RichCommand](https://github.com/ewels/rich-click/blob/8e7523c891e0d3132f3c49e98154945e371d5e9b/src/rich_click/rich_command.py#L11), appears to be a a single block of code.

class click.MultiCommand(Command) overrides .format_options() which calls the parent's .format_options() and then its own [.format_commands()](https://github.com/pallets/click/blob/d0af32d8e7d78f4fdaf9c3d1559e1ffaac1b2569/src/click/core.py#L1599) which does three things when outputting the subcommands: 
1. ignores empty commands (loading function returned None)
2. ignores commands with the .hidden property
3. Adds "extra space" between command name and the short help string

Perhaps 1. and 2. can/should be added to rich_format_help() (unless the logic already exists), but it seems that it works fine on MultiCommands as it is. A simple solution to @nilsvu's problem seems to be overriding the .format_help() of MultiCommand by the same code used in [rich_click.Command](https://github.com/ewels/rich-click/blob/8e7523c891e0d3132f3c49e98154945e371d5e9b/src/rich_click/rich_command.py#L76) (as suggested by @ewels). This solution works fine for me.

```python
class Cli(click.MultiCommand):
    ...
    def format_help(self, ctx: click.Context, formatter: click.HelpFormatter):
        rich_format_help(self, ctx, formatter)
```

**Comment by nilsvu** [comment]
Thanks @hsunner, that's very helpful and works well! Sounds like simply subclassing `click.MultiCommand` and overriding `format_help` and `main` like for the standard command would do it.

**Comment by dwreeves** [comment]
We can have a slightly better and more "official" solution for this shortly. TLDR: it should be straightforward to add a `rich_click.RichMultiCommand` object in 1.7.0. Stay tuned.
