### ISSUE TITLE
Negative `--no-*` option variant not showing up

### ISSUE THREAD

**Issue by taranlu-houzz** [ewels/rich-click#45]
It seems that the `--no-*` variants for options are not showing up for me... I took the same example from #31 and it produces the following result when I run it:

![image](https://user-images.githubusercontent.com/52425255/159078897-ed3dfa11-2cfa-4b91-8a6d-f63172519241.png)

These are the versions of `rich` and `rich-click` installed in the virtualenv:
- `rich`: 10.16.2
- `rich-click`: 1.2.1

**Comment by ewels** [comment]
Yes I noticed the same thing earlier today. I'm pretty sure that earlier versions did use to work, so I guess I broke it recently-ish.

Thanks for reporting, I'll take a look into it when I get a chance 👍🏻 (PRs welcome)

**Comment by Benjamin-Lee** [comment]
Came to report this just now as well. Glad to see I'm not the only one.
