### ISSUE TITLE
Add option to default to "standard" click

### ISSUE THREAD

**Issue by swaldhoer** [ewels/rich-click#47]
Building a cli tool with ``rich-click`` is super cool - at least if you as a developer like rich formatting on the terminal.
But then there are users, who like your tool, but don’t like all the fancy stuff and that’s a reasonable opinion.

Therefore ``rich-click`` should add an option (maybe even by default) that lets you disable all the richiness and actually replaces the rich_click import with an actual click import, e.g., something like that

```python
@click.option(
    "--rich/--no-rich",
    is_flag=True,
    default=True,
    help="Use rich terminal output (default: rich).",
)
```

**Comment by ewels** [comment]
> and that’s a reasonable opinion.

I'm not sure that I agree to be honest. A lot of terminal tools have stylised terminal output. I would argue that it's up to the tool developer to choose how it renders in the terminal.

Note that rich itself is pretty clever about adapting output according to the environment that it's running in. So the help should have no problems when being piped to other tools or running in weird environments. Rich also listens to [certain environment variables](https://rich.readthedocs.io/en/stable/console.html#environment-variables) such as `$NO_COLOR` so the end user can disable colours fairly easily if they wish.

> Therefore `rich-click` should add an option (maybe even by default) that lets you disable all the richiness and actually replaces the rich_click import with an actual click import

I'm not sure that the cli option would be possible in fact, as to parse it you have to use click. So by the time you know whether it was set or not, click (or rich-click) must already be imported.

Developers can always add logic to their packages to make the imports configurable based on the presence or absence of an environment variable though (or other means). I don't think that this needs to be within the rich-click package itself.

Do you have a specific use case that you're thinking of when requesting this feature?

Cheers,

Phil

**Comment by swaldhoer** [comment]
Thanks for your detailed answer. I had a look at the ``NO_COLOR`` and ``TERM`` env vars ``rich`` respects, and this is basically what I wanted to achive . Thanks for pointing that out.

Best regards

**Comment by ewels** [comment]
Ok great! Glad to hear it :)
