### ISSUE TITLE
[Feature] `rich_click.cli.patch()`

### ISSUE THREAD

**Issue by dwreeves** [ewels/rich-click#53]
I have the following use case: I want to take another Python library's CLI, make some slight changes, and add it to my app's CLI with `click.Group.add_command()`.

In order to get that library using Rich-Click, I need to patch manually. This is my `__main__.py`:

```python
# __main__.py
from rich_click import command as rich_command
from rich_click import group as rich_group
from rich_click import RichCommand
from rich_click import RichGroup

import click

click.group = rich_group
click.command = rich_command
click.Command = RichCommand
click.Group = RichGroup

# this is where my CLI is.
from app.cli import cli


cli()
```

Instead, what we could do is have a function called `patch()` that does this. Here is what I am thinking:

```python
# __main__.py
from rich_click.cli import patch

patch()

# this is where my CLI is.
from app.cli import cli

cli()
```

This doesn't need to be a majorly advertised feature-- using it the way I want to is a bit niche-- and it can and should take a back seat to the rich-click CLI. The main use of this would be internally inside `rich_click.cli.main`, where the following lines of code...

```python
    if len(args) > 1:
        if args[1] == "--":
            del args[1]
    sys.argv = [prog, *args[1:]]
    # patch click before importing the program function
    click.group = rich_group
    click.command = rich_command
    click.Group = RichGroup
    click.Command = RichCommand
    # import the program function
    module = import_module(module_path)
    function = getattr(module, function_name)
    # simply run it: it should be patched as well
    return function()
```

... could instead look like this ...

```python
    if len(args) > 1:
        if args[1] == "--":
            del args[1]
    sys.argv = [prog, *args[1:]]
    # patch click before importing the program function
    patch()
    # import the program function
    module = import_module(module_path)
    function = getattr(module, function_name)
    # simply run it: it should be patched as well
    return function()
```

where `patch()` is defined as (you guessed it):

```python
def patch() -> None:
    """Patch Click internals to use Rich-Click types."""
    click.group = rich_group
    click.command = rich_command
    click.Group = RichGroup
    click.Command = RichCommand
```

But I suggest separating out the patching function so that it can be exposed for niche situations like the case I'm working on.

WDYT?

**Comment by ewels** [comment]
Sure - so this is essentially refactoring the code with no change to current behaviour so that it can be better accessed by other tools..? I don't see any downsides.. 🤔 

Fancy putting in a PR?

**Comment by dwreeves** [comment]
Yes, exactly! And I can do that!
