### ISSUE TITLE
`rich_cli` does not properly clean indentations for `click >= 8.1.0`

### ISSUE THREAD

**Issue by apcamargo** [ewels/rich-click#55]
`rich_click` is not cleaning indentations if `click` version is ≥ 8.10. The cause is probably [this change](https://github.com/pallets/click/issues/1985) in the backend.

This code:
```python
def cli():
    """
    Foo: bar

    Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod
    tempor incididunt ut labore et dolore magna aliqua. Pellentesque habitant
    morbi tristique senectus. Leo a diam sollicitudin tempor.
    """
```

Is generating this:
```
 Foo: bar
 Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod     tempor incididunt ut
 labore et dolore magna aliqua. Pellentesque habitant     morbi tristique senectus. Leo a diam
 sollicitudin tempor.
```

Instead of this:
```
 Foo: bar
 Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore
 et dolore magna aliqua. Pellentesque habitant morbi tristique senectus. Leo a diam sollicitudin
 tempor.
```

**Comment by ewels** [comment]
Ok, so we need to run dedent manually now I guess. Thanks for reporting! PRs welcome, I'm away for 2-3 weeks now with holiday and starting a new job but will get to it ASAP.

**Comment by apcamargo** [comment]
I'll try to take a look at the code in the next few days. But it seems to me that the easy way out would be to use `inspect.cleandoc` within `_make_rich_rext`. Do you think this would beak something?

**Comment by ewels** [comment]
No, that sounds perfect 👍🏻  I wasn't familiar with `inspect.cleandoc`, I didn't realise that this was part of the core lib. I've used `textwrap.dedent` in the past which is why that jumped to mind. But better to use the same approach as Click 👍🏻

**Comment by abdusco** [comment]
@apcamargo 's fix works wonderfully 🚀

**Comment by apcamargo** [comment]
@ewels I'm still having this issue in the latest version :(
@abdusco, how did you test the PR?

**Comment by apcamargo** [comment]
Ok. Apparently the fix worked for the header, but not for the command description.

```
 Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut
 labore et dolore magna aliqua. Pellentesque habitant morbi tristique senectus. Leo a diam
 sollicitudin tempor.

╭─ Options ────────────────────────────────────────────────────────────────────────────────────────╮
│  --version      Show the version and exit.                                                       │
│  --help     -h  Show this message and exit.                                                      │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
╭─ Modules ────────────────────────────────────────────────────────────────────────────────────────╮
│  download-database          Download the latest version of Genomad's database and save it in     │
│                             the     DESTINATION directory.                                       │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
```

**Comment by ewels** [comment]
ah yeah, tests... https://github.com/ewels/rich-click/issues/25 🙄 

Thanks for spotting @apcamargo! I also spotted one other place in the code that needed this before release ([`0f99123`](https://github.com/ewels/rich-click/commit/0f991233e480c03e621b2f7ea0f846fdda228999#diff-738a2a418c0833585666208ca8a8c9e73b3cd275586e21094d7be7f0fc51dd8fR164-R165)), but missed this one..
