### ISSUE TITLE
Typer autocomplete on constructor

### ISSUE THREAD

**Issue by Kludex** [ewels/rich-click#57]
I want to have autocompletion when instantiating a `Typer` object.

Can I open a PR with it? It will be verbose.

**Comment by ewels** [comment]
Sure! I'm not very familiar with Typer so I'm not entirely sure what you mean, but go for it.

Note that if / when Typer gets native support for rich-click (or something like it), I will remove Typer support from this library. Just so you know :)

I'm about to head off on holiday and then start a new job, so be warned that it'll likely be at least a couple of weeks before I get to reviewing anything 👍🏻

**Comment by Kludex** [comment]
> Note that if / when Typer gets native support for rich-click (or something like it), I will remove Typer support from this library. Just so you know :)

Noted.

> Sure! I'm not very familiar with Typer so I'm not entirely sure what you mean, but go for it.

When you instantiate the `Typer` object, you don't have autocomplete because the `rich_click.typer.Typer.__init__` uses args and kwargs:

<img width="644" alt="image" src="https://user-images.githubusercontent.com/7353520/163667670-2ee03488-e71a-489f-be62-9b2b2fc67011.png">

My goal is to not have to check what `Typer` parameters are accepted elsewhere.

> I'm about to head off on holiday and then start a new job, so be warned that it'll likely be at least a couple of weeks before I get to reviewing anything 👍🏻

That's exciting! Have a pleasant holiday, and enjoy your new adventure! 🤩

I'll be opening a PR at some point - if someone is reading this, and want to do it, go ahead.

**Comment by ewels** [comment]
Closing for now, can reopen if there is a lot of interest.
