### ISSUE TITLE
`\f` does not work when `USE_MARKDOWN=True`

### ISSUE THREAD

**Issue by cazador481** [ewels/rich-click#60]
In click using the `\f` ignores all text after that point in the help.  When doing using non markdown mode this works, but when I enable markdown the text shows up.

**Comment by ewels** [comment]
Thanks for reporting!

I'm testing now and I can't get `\f` to have any effect ever! 🤔 Seems to work as expected with older versions of click still. So I think I need to reimplement this one myself either way.. 😀

**Comment by ewels** [comment]
Ok should now work as expected. Let me know if you hit any issues!

Phil
