### ISSUE TITLE
`click.Command` option `hidden=True` is ignored

### ISSUE THREAD

**Issue by lgprobert** [ewels/rich-click#61]
`click.Command` in Click 8.1 has a option `hidden=True` to make the command hidden from help message, which is similar to the behavior like hidden argument in click.Option.

While `hidden=True` works well with click command option, it is ignored when commands have this option. All commands with this option are shown in help message.

This symptom is always reproducible.

Thanks

**Comment by lgprobert** [comment]
After looking into source codes in core.py from click and compare to the rich_format_help() method from rich_click.py, I believe this issue can be easily solved by adding below lines to line 477 of rich_click.py:

```python
          if cmd.hidden:
                continue
```
The above lines are copied from `MultiCommand.format_commands()` from core.py.

Hope this can save some time to fix this issue and have a new fix release sooner as this is quite useful.

Thanks

**Comment by ewels** [comment]
Nice, thanks for reporting! I've wanted something like this from Click for a while, great to see that it's been added 👍🏻

**Comment by lgprobert** [comment]
Glad that can do some help. This project is awesome!

**Comment by ewels** [comment]
I probably won't have time to add this for a couple of weeks (starting a new job), so if you fancy putting a pull-request in with the change that would be great 👍🏻  Otherwise I'll get to it ASAP.

Phil

**Comment by lgprobert** [comment]
Sure, has filed a PR with the changes to you. Please look. Thanks
