### ISSUE TITLE
Return value from Typer function is printed only when installed 

### ISSUE THREAD

**Issue by Benjamin-Lee** [ewels/rich-click#63]
I apologize in advance for how obscure this bug is.

I'll start by taking the simple Typer demo and modifying it to have `download` return a string:

```python

import rich_click.typer as typer

app = typer.Typer()

@app.command()
def sync(
    type: str = typer.Option("files", help="Type of file to sync"),
    all: bool = typer.Option(False, help="Sync all the things?"),
):
    print("Syncing")


@app.command()
def download(all: bool = typer.Option(False, help="Get everything")):
    return "Shouldn't appear" # <-- RETURNS A STRING NOW


if __name__ == "__main__":
    app()
```

When run directly, everything is normal:

```
$ python vdsearch/test.py download
$
```

Now let's `pip install -e .` with `testy` mapped to `test:app`

```
$ testy download
Shouldn't appear
$
```

I've gotten around this bug by defining wrapper functions for my functions but it would be nice to get to the bottom of what's going on.

**Comment by ewels** [comment]
Strange! And to confirm, this doesn't happen when you just do `import typer`?

**Comment by mcflugen** [comment]
I'm seeing the same thing but using *click*.
```python
import rich_click as click


@click.group(chain=False)
def app():
    pass


@app.command()
def sync():
    print("Syncing")


@app.command()
def download():
    print("Downloading")
    return "Shouldn't appear"


if __name__ == "__main__":
    app()
```
As with @Benjamin-Lee, if I run the program as a script, it runs as expected,
```bash
$ python testy.py sync
Syncing
$ python testy.py download
Downloading
```
But if the script is *pip*-installed as an entry point and then run, the return values of the functions are printed,
```bash
$ testy sync
Syncing
$ testy download
Downloading
Shouldn't appear
```
Now if I set `chain=True`, I get the return values as part of a list,
```bash
$ testy sync
Syncing
[None]
$ testy download
Downloading
["Shouldn't appear"]
$ testy sync download
Syncing
Downloading
[None, "Shouldn't appear"]
```
My solution is to turn subcommand chaining off and make sure my subcommand functions don't return anything, which works ok but isn't ideal.

Oh, these extra strings are being sent to *stderr*,
```bash
$ testy download 2> /dev/null
Downloading
```

**Comment by ewels** [comment]
If you could confirm whether this is specifically due to `rich-click` and not the underlying `click` package (which Typer also uses under the hood) that would be great.

My suspicion is that it's not related to the code in this repo but rather the underlying library. But I could be wrong :)

**Comment by mcflugen** [comment]
@ewels, sorry, I forgot to mention that I've only seen this behavior when I use *rich-click*, unfortunately. So if in my example I replace `import rich_click as click` with `import click`, the extra output disappears.

**Comment by mcflugen** [comment]
@ewels It appears the problem may have to do with the use of the *standalone_mode* keyword in `RichCommand`. If I replace the [super call in `RichCommand.main`](https://github.com/ewels/rich-click/blob/32130e54edb885db2ab40fec7974dbad2dfc828b/src/rich_click/rich_command.py#L19) with,
```python
return super().main(*args, standalone_mode=True, **kwargs)
```
the extra output disappears.

**Comment by ewels** [comment]
Ok thanks for investigating 👍🏻 Hmm. Now why did I add that there... 🤔🙈 Pretty sure that there was a reason but I can't remember why now!

**Comment by ewels** [comment]
Awesome. Thanks @mcflugen!
