### ISSUE TITLE
Fix pylance type errors

### ISSUE THREAD

**Issue by Hexiro** [ewels/rich-click#64]
By default, when trying to modify rich_click options, pylance reports this:
![image](https://user-images.githubusercontent.com/42787085/166160294-0fdd03af-6c43-4e3f-b3a7-722bbd2aa526.png)

To fix this, you can add this line to the imports of rich_click.py:
![image](https://user-images.githubusercontent.com/42787085/166160322-1487fb90-2991-415a-81de-7abb2d33259b.png)

After:
![image](https://user-images.githubusercontent.com/42787085/166160345-37208d70-c92a-4bea-891a-0609b9e33a36.png)

I'm not sure the implications of using a dot import here, and I'm also not sure if there's another way to fix this, but this is a pretty simple fix. If you wouldn't like to add this I could just patch it in my own install for development purposes, but I'm sure some others could benefit from this.

**Comment by ewels** [comment]
Interesting - confirmed at my end. I'm kind of surprised that more stuff doesn't break _without_ this in place..? 🤔 😅 

Agree that it's a useful addition. Aside from the avoiding the error it also means that auto-suggestions of attributes etc work properly.

Thanks!
