### ISSUE TITLE
`rich-click` doesn't support `click.Choice`

### ISSUE THREAD

**Issue by apcamargo** [ewels/rich-click#68]
I'm writing a command which has a `--composition` parameter that uses `click.Choice`:

```python
@click.option(
    "--composition",
    type=click.Choice(["auto", "metagenome"], case_sensitive=False),
)
```

In vanilla `click`, the possible choices appear as expected:

```
Options:
  --version                       Show the version and exit.
  --composition [auto|metagenome]
  -v, --verbose / -q, --quiet     Display the execution log.  [default:
                                  verbose]
  -h, --help                      Show this message and exit.
```

`rich-click` omits the options:

```
╭─ Basic options ──────────────────────────────────────────────────────────────────────────────────╮
│  --composition                                                                                   │
│  --verbose/--quiet  -v/-q  Display the execution log. [default: verbose]                         │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
╭─ Other ──────────────────────────────────────────────────────────────────────────────────────────╮
│  --help     -h  Show this message and exit.                                                      │
│  --version      Show the version and exit.                                                       │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
```

**Comment by apcamargo** [comment]
My mistake. This happened because I disabled the metavars column.

```python
click.rich_click.SHOW_METAVARS_COLUMN = True
````

**Comment by ewels** [comment]
No worries!

Note that if you'd rather not have the metavars column but instead have the metavars inline with the help, you can set:

```python
click.rich_click.SHOW_METAVARS_COLUMN = False
click.rich_click.APPEND_METAVARS_HELP = True
```

See `examples/click/08_metavars.py` for an example:

<img width="890" alt="Screenshot 2022-05-16 at 10 09 10" src="https://user-images.githubusercontent.com/465550/168547874-529001a4-107c-4053-a751-4dc496976e24.png">

**Comment by ewels** [comment]
You're also not the first person to miss the mention of this in the readme. I added the search term "option choices" to the header last time to make the fairly non-obvious "metavars" easier to find, but let me know if you have any ideas for how else to improve it: https://github.com/ewels/rich-click#metavars-and-option-choices

**Comment by apcamargo** [comment]
To be honest, I'm 100% sure this was not a problem with the documentation. I had read all the customization options before and simply forgot about them. But maybe you could add a TOC in the beginning of the README? This way users wouldn't need to scroll all the way down to see that there are tons of customization options available.

**Comment by ewels** [comment]
Yup, not a bad idea. I've gone off manual ToCs a bit since GitHub added their markdown dropdown header menu, as they're a pain to keep up to date. But I agree that it would be nice to aid visibility here.

Looking at the readme I should probably add more mention of Typer to the intro as well..
