### ISSUE TITLE
Markup and rich formatting in click.echo

### ISSUE THREAD

**Issue by cadojo** [ewels/rich-click#73]
Is there any way to print rich-formatted types and text in the body of a command with `click.echo`?

**Comment by ewels** [comment]
I'm not sure I really understand sorry. Could you add a small code snippet showing what you would like to happen please?

**Comment by cadojo** [comment]
Sure! My understanding of this package is it provides rich-text formatting to click help screens, error displays, etc. I would like to also print rich-formatted text in the body of each command, like my use of `click.echo` below. 

```python
import rich_click as click
click.rich_click.USE_RICH_MARKUP = True

@click.command()
def cli():
    """A helpful CLI."""
    ...
    ... # doing stuff...
    ...

    click.echo("[bold green]Success!![/]") 
```

But the code above outputs the literal `"[bold green]Success!![/]"` string. Is there any way to rich-format that text in the body of the command?

**Comment by ewels** [comment]
Oh I see! By body you just mean the output of the tool itself. This is kind of beyond the scope of rich-click as it's no longer to do with the click command-line interface handling - it's just the main content of your program. However I can see the confusion as you're using a click utility function in your example (you could use this anywhere, with or without a command line interface).

Anyway, the easiest way to do this is to just [use rich directly](https://rich.readthedocs.io/en/stable/introduction.html#quick-start):

```python
import rich_click as click
from rich import print

@click.command()
def cli():
    """A helpful CLI."""
    ...
    ... # doing stuff...
    ...

    print("[bold green]Success!![/]") 
```

Does this make sense? Hope this helps!

**Comment by cadojo** [comment]
Oh man I hadn't tried that. I had tried a regular `print` statement and I didn't see any output, but I'm guessing that was a `click.group` configuration issue, I had never used `click` before. 


Thanks for the help!

**Comment by ewels** [comment]
I think regular `print()` should work as well 🤔 See the [basic example](https://github.com/ewels/rich-click/blob/main/examples/click/01_simple.py) which does this.

Anyway, I'll close now if you're happy 😄 Shout if you run into any issues!
