### ISSUE TITLE
Hyperlinks seems not working when using with Typer

### ISSUE THREAD

**Issue by AlirezaTheH** [ewels/rich-click#80]
Hi @ewels,
When I use `rich-click` with Typer, both Markdown and Rich markup style won't get me a working clickable hyperlink.

By using:
```python
"""See [here](https://en.wikipedia.org/wiki/List_of_ISO_639-2_codes)"""
```

I get something like this:
![Screen Shot 2022-07-03 at 02 20 55](https://user-images.githubusercontent.com/17493246/177017080-b535e91d-9aa2-4915-9784-56e9a47963cb.png)

As you can see the word *here* is colored but it's not a link.

I've also tested different shells (zsh, bash) to see if there is a problem with shell but it's not.

**Comment by ewels** [comment]
You need to ctrl+click (cmd+click for Mac) for the link to work - are you doing that?

It's the terminal _program_ that's important (eg. iTerm2, Terminal.app, Putty, etc etc), not the shell (bash, zsh). So it's also possible that the terminal program you're using doesn't support links.

**Comment by AlirezaTheH** [comment]
It's Terminal.app and I know that it supports links. For normal links you can click on them with cmd + double click.

**Comment by ewels** [comment]
Yup, I just checked and it looks like `Terminal.app` doesn't support rich hyperlinks (normal links are different). I can confirm that I get the same behaviour (purple text, not highlighted) if I run `python examples/click/05_markdown.py --help` in `Terminal.app`, but with [iTerm2](https://iterm2.com) it works fine.

So, nothing I can do sorry - only fix is to use a different terminal emulator 🤷🏻‍♂️ 

Note that this is not specific to rich-click, but rather the underlying [rich](https://github.com/Textualize/rich) library.
