### ISSUE TITLE
Are custom group classes supported?

### ISSUE THREAD

**Issue by WHTJEON** [ewels/rich-click#81]
This seems to not work when I assign a custom class to a `click.group` object with `cls=(name)` parameter. 
Is there a workaround for this?

**Comment by ewels** [comment]
Yup, see the "declarative" section of the readme:

> Declarative
> 
> If you prefer, you can `RichGroup` or `RichCommand` with the `cls` argument in your click usage instead. This means that you can continue to use the unmodified click package in parallel.
> 
> > See [examples/click/02_declarative.py](https://github.com/ewels/rich-click/blob/main/examples/click/02_declarative.py) for an example.

https://github.com/ewels/rich-click#declarative

And the example:

```Python
import click

from rich_click import RichCommand, RichGroup


@click.group(cls=RichGroup)
@click.option("--debug/--no-debug", default=False)
def cli(debug):
    """
    My amazing tool does all the things.

    This is a minimal example based on documentation
    from the 'click' package.

    You can try using --help at the top level and also for
    specific group subcommands.
    """
    click.echo(f"Debug mode is {'on' if debug else 'off'}")


@cli.command(cls=RichCommand)
def sync():
    """Synchronise all your files between two places."""
    click.echo("Syncing")


if __name__ == "__main__":
    cli()
```

So if you want to use your own custom class, just make it inherit from `RichGroup` and it should work.

phil

**Comment by pawelad** [comment]
For whoever looks for it in the future - this helped me make [click-default-group](https://github.com/click-contrib/click-default-group) work with `rick-click`:


```python
from click_default_group import DefaultGroup
from rich_click import RichGroup


class DefaultRichGroup(DefaultGroup, RichGroup):
    """Make `click-default-group` work with `rick-click`."""
```
