### ISSUE TITLE
Hide env var defaults for automatically generated completion flags

### ISSUE THREAD

**Issue by taranlu-houzz** [ewels/rich-click#84]
By default, `typer` (or maybe `click`?) adds two default flags to generate or show the completions for a given shell. When generating the help, `rich-click` seems to show the env var info for these flags by default:
![image](https://user-images.githubusercontent.com/52425255/178446394-1157a339-a441-44c1-8043-e842e668796a.png)

For user defined functions, one can just add `show_envvar=False` but I don't think that appears to be an option for the automatically generated flags. Also, when just using `typer`, the env var help info is not printed for these flags.

**Comment by ewels** [comment]
Hi @taranlu-houzz,

Thanks for reporting this! I've just pushed a change so that rich-click now only prints the env vars if they are not `None`. This seems to resolve your issue.

Let me know if you hit any problems with it.

Phil
