### ISSUE TITLE
Untyped decorator issue with rich-click

### ISSUE THREAD

**Issue by cheginit** [ewels/rich-click#85]
Click used to have this issue with static type checker:

```
Untyped decorator makes function "cli" untyped
```

They [addressed](https://github.com/pallets/click/pull/2256) this issue but when I switched to using `rich-click`, I am getting this error message again when running `mypy`.

**Comment by ewels** [comment]
I'm not a big mypy user (as in, I've not used it and don't use it) so this isn't a fix that comes easily to me. If you're able to put in a PR to solve the issue, that would be great 🙏🏻 

Thanks!

**Comment by cheginit** [comment]
Sure, will give it a try!

**Comment by dwreeves** [comment]
All typing issues should have hopefully been resolved with #126, and will be released in 1.7.

All rich-click decorators will now have full typing parity with click 8.x, meaning if a static type check works in click 8.x then it should also work in rich-click 1.7.

**Comment by cheginit** [comment]
Great, thank you. I will give it a try!
