### ISSUE TITLE
Provide help message when --help is used in a cli with required arguments

### ISSUE THREAD

**Issue by girivs82** [ewels/rich-click#87]
When building a cli with a required argument, when the command is specified without the required argument, rich-click prints the error as expected. But there is an exception to this, which is when the user tries to run the command with `--help`.

In this case, the user is aware that an argument is required, but wants to get the full help, but because the required argument is not passed, the required argument error shows instead of the help message.

I submit that using `--help` is a valid case where the required argument error should not override the following behaviour, which is the printing of the help string.

To be fair, the same issue occurs in click as well, but there is a workaround for that in click which is to override the UsageError show method as shown in the SO link: https://stackoverflow.com/questions/39596070/python-click-custom-error-message

How do I do something similar with rich-click?

**Comment by ewels** [comment]
Hi @girivs82,

Thanks for creating the issue! I agree that `--help` feels like a special case 👍🏻 

There are two ways that you can use `rich-click` - the simpler `import rich_click as click` or the more verbose declarative method (`import click; from rich_click import RichCommand, RichGroup`). There's an example of the latter in [`examples/02_declarative.py`](https://github.com/ewels/rich-click/blob/main/examples/02_declarative.py). This method is basically native `click` so you should be able to a similar workaround with this.

Longer term, I think it would be interesting in looking into whether we can implement this natively within `rich-click`. Any contributions along these lines would be welcome.

Phil

**Comment by girivs82** [comment]
Thanks! I will try the declarative method and wait for any native implementation of this. I'll also look at the source to see if I can help contribute to this issue in some way.

**Comment by dwreeves** [comment]
@girivs82 Can you provide a minimum working example, show what happens (just the console output works), and what you expect/want to happen? I'm not 100% following. 😅

It looks like the StackOverflow issue you are discussing is relating to Click versions prior to version 7.

For example, I run the example code in StackOverflow with Click 8:

```
>> python foo.py
Usage: foo.py [OPTIONS] <analysis directory>
Try 'foo.py --help' for help.

Error: Missing argument '<analysis directory>'.
```

Using Click 6, I see:

```
>> python foo.py
Usage: foo.py [OPTIONS] <analysis directory>

Error: Missing argument "analysis_dir".
```

At least, as of the most recent version of rich-click running in Click 8, again using the example in StackOverflow, I get this:

```
>> python foo.py                                       

 Usage: foo.py [OPTIONS] <analysis directory>                    
                                                                 
 Try 'foo.py -h' for help.                                       
╭─ Error ───────────────────────────────────────────────────────╮
│ Missing argument '<analysis directory>'.                      │
╰───────────────────────────────────────────────────────────────╯
```

and

```
>> python foo.py --help

 Usage: foo.py [OPTIONS] <analysis directory>                    
                                                                 
 Do stuff                                                        
                                                                 
╭─ Options ─────────────────────────────────────────────────────╮
│ --help  -h    Show this message and exit.                     │
╰───────────────────────────────────────────────────────────────╯
```

As far as I can tell, the following two things are true: (1) the StackOverflow issue is in reference to an old behavior that is no longer true of click starting with click 7.0, and (2) rich-click does display a message telling the user to use a flag to get help.

**Comment by dwreeves** [comment]
I believe this is not an issue with Click 7+. If this still is an issue, let me know and I will re-open, although minimal example would be helpful.
