### ISSUE TITLE
Make `rich-click` extensible and isolate configuration state

### ISSUE THREAD

**Issue by BrutalSimplicity** [ewels/rich-click#89]
Right now all of the functions in the `rich_click` module are difficult to override and extend behavior unless you extend one of the `RichCommand` or `RichGroup` classes. And even then, you can't really get access the the internals since the `formatter` is not being used and the results of `rich_format_help` are not returned to the caller.

It would be nice if the Rich `Console` and `rich_click` configuration state could be configured/extended through class inheritance.

This leads to two implementation changes.
- One, move this behavior into a class with the configuration state encapsulated in the class.
- Two, create extensible methods that allow one to change the `Console` configuration and/or results of certain formatting functions.

For the first item, I think it might be possible to provide a class implementation of the formatter that could contain the state, and then expose a new method on the `Context` object that would allow you to configure the formatter before making the call to `rich_format_help`. For the most part, the module state is not a big problem since help generation is fired only once before application termination. However, one issue I've found is that letting the configuration sit in module state makes testing help messages difficult, since state changes leak across tests. I think it's also generally good practice to isolate state, and will make this library more reusable across the `Click` ecosystem.

I think the changes for one would solve most of the issues with two. If you implement the `formatter` interface, others could hook into that functionality, and it could be configured along with whatever method or attribute you expose on the `Context`.

**Comment by ewels** [comment]
Sounds sensible 👍🏻  Do you think it would be possible to do this in a backwards-compatible manner for anyone who is already extending those classes?

**Comment by BrutalSimplicity** [comment]
I took a stab at this yesterday evening. I'll submit my PR for initial review later today.

**Comment by BrutalSimplicity** [comment]
Opened a PR for this that coincidentally seems to tackle quite a few other issues

#25 #90 #88 #29 #18
