### ISSUE TITLE
Can you release a new version that includes COMMANDS_GROUP in pypi?

### ISSUE THREAD

**Issue by Ambro17** [ewels/rich-click#9]
I was reading the README, tried the COMMAND_GROUPS functionality but nothing happened. After inspecting the lib source, it seems it doesn't have the latest code from the repo main branch

Thank you for creating this lib!!

**Comment by ewels** [comment]
Yes sorry - I am on holiday at the moment and wrote that code on the plane (offline). I pushed the code when I got to wifi but haven't had a chance to do a release yet.

**Comment by Ambro17** [comment]
No problems, thank you! I'll wait patiently

**Comment by ewels** [comment]
ok done: https://github.com/ewels/rich-click/releases/tag/v0.3.0

https://pypi.org/project/rich-click/0.3.0/
