### ISSUE TITLE
click.ClickException should output to stderr

### ISSUE THREAD

**Issue by mjkanji** [ewels/rich-click#90]
`rich_click` override's `click`'s default (and correct) behavior of writing exceptions (e.g., `raise click.ClickException('There's a problem!')`) to stderr. This has implications for CI/CD, for example, where a `rich_click` application may raise an exception but because it's being output to stdout, the task still passes.

**Comment by ewels** [comment]
Any ideas on how we can do this whilst still using our own `rich` console? If we defer errors to click I'm not sure how we would be able to keep control over output to the terminal.

**Comment by ewels** [comment]
Oh wait, I think I misunderstood. You just mean terminal output from errors is currently going to stdout and it should be stderr? I see no problem with that..

**Comment by mjkanji** [comment]
> Oh wait, I think I misunderstood. You just mean terminal output from errors is currently going to stdout and it should be stderr? I see no problem with that..

That's exactly it! As for the implementation, Rich already supports created consoles that output to stderr. Please see here:

https://rich.readthedocs.io/en/stable/console.html#error-console

The `rich.print` function also supports setting `file=sys.stderr` to achieve the same.

**Comment by ewels** [comment]
Yup, should be pretty simple 👍🏻 Will get to it when I can, or if you fancy putting in a PR that would be even better. It'd be nice to emulate native click behaviour.

Note that I still don't 100% understand how this impacts CI/CD.. You just mean that the tests would be listening to stderr and so miss the output? They could equally listen to stdout, no? But it doesn't really matter, I think it would be a good change either way.

Phil
